window.POEMS_DATA = [
  {
    "id": 1,
    "title": "Kayeu Chan Timro Lagi Pani",
    "subtitle": "There are more hearts that quietly hold you than you'll ever know.",
    "slug": "kayeu-chan-timro-lagi-pani",
    "caption": "A gentle reminder that even when love feels lost, you are still cherished in countless unseen ways.",
    "quote": "Kayeu chan timro lagi pani.",
    "category": "Hope",
    "tags": [
      "hope",
      "love",
      "healing",
      "memories",
      "self-worth",
      "kindness"
    ],
    "mood": "hopeful",
    "duration": "50 sec",
    "readingTime": "1 min",
    "publishDate": "2025-07-26",
    "featured": true,
    "thumbnail": "assets/thumbnails/kayeuchantimrolagipani.jpg",
    "heroImage": "assets/thumbnails/kayeuchantimrolagipani.jpg",
    "video": "assets/videos/kayeuchan.mp4",
    "poster": "assets/thumbnails/kayeuchantimrolagipani.jpg",
    "audioOnly": false,
    "fullPoem": "Kayeu chan timro lagi pani.\n\nGhumayeko prem,\nPayera pani harayeka yaad haru,\nFarkauna khojne timi.\n\nBigat thiyo ra ta timi chau,\nAni timi chau ra ta yi yaad haru chan.\nYei yaad ma bacheka hau,\nTinlai birsina chai nakhojnu hai timi.\n\nU farki aaune aasha ta didina ma,\nTara ekai juni na ho,\nBheti po halchau ki kunai din.\n\nU nafarke pani,\nFarkine aasha chai namarnu hai timi.\n\nBiteka din nai ta hun,\nSamjhi musukka muskurai dinu.\nSamjhaunu aafno man lai,\nAni samjhinu,\nAafu pani ek palta timi.\n\nKayeu chan timro lagi pani.",
    "meaning": "This poem is about hope after heartbreak. It reminds us that although some people leave and some memories remain unfinished, our lives are still filled with people who quietly care for us. Even when love seems absent, kindness, gratitude, and affection continue to exist in places we may never notice.",
    "authorNotes": "I wrote this for everyone who has ever believed they were unloved. Sometimes we become unforgettable to people without ever realizing it.",
    "inspiration": "The realization that we are remembered not only by those we loved, but also by strangers, friends, teachers, and people whose lives we touched for only a moment.",
    "instagramUrl": "https://www.instagram.com/uwyiz_/",
    "shareUrl": "https://yourdomain.com/poems/kayeu-chan-timro-lagi-pani",
    "views": 0,
    "likes": 0,
    "bookmarks": 0,
    "relatedPoems": [
      1,
      5
    ],
    "seoTitle": "Kayeu Chan Timro Lagi Pani | A Poem About Hope and Quiet Love",
    "seoDescription": "A heartfelt Nepali spoken-word poem reminding us that we are loved, remembered, and cherished in more ways than we often realize.",
    "altText": "A warm golden sunset with a solitary figure smiling gently, symbolizing hope after heartbreak.",
    "colorTheme": "#D8A76A",
    "language": "Nepali",
    "visibility": "published",
    "draft": false
  },
  {
    "id": 3,
    "title": "Bilauney Chan Yi Yaad Haru",
    "subtitle": "Parkhai ko pachhiltira, sayau sapana pachhadai...",
    "slug": "bilauney-chan-yi-yaad-haru",
    "caption": "A farewell to thirteen years of memories, friendships, classrooms, and the place that quietly became home.",
    "quote": "Samjhana mai samhalnu hai malai.",
    "category": "Nostalgia",
    "tags": [
      "nostalgia",
      "school",
      "friendship",
      "farewell",
      "memories",
      "growing-up"
    ],
    "mood": "nostalgic",
    "duration": "1 min 26 sec",
    "readingTime": "2 min",
    "publishDate": "2025-01-24",
    "featured": true,
    "thumbnail": "assets/thumbnails/bilauney chan yi yaad haru.jpg",
    "heroImage": "assets/thumbnails/bilauney chan yi yaad haru.jpg",
    "video": "assets/videos/bilauney chan yi yaad haru.mp4",
    "poster": "assets/thumbnails/bilauney chan yi yaad haru.jpg",
    "audioOnly": false,
    "fullPoem": "Parkhai ko pachhiltira,\nSayau sapana pachhadai,\nParkhaune ra parkhirahaneharu ko lagi...\n\nYaad rakhnu,\nBilauney chan yi yaad haru.\n\nAajhai pani samjhinchu ma tyo Saraswati Pooja ko din,\nAankha bhari aashu,\nMero haat samatera ka, kha, ga lekhna sikaaunu bhayeko\nMero aadarniya guru.\n\nYi harsha ra sangharsha le bhariyeka 13 barsaka yaad,\nAba sayad samjhanama matrai sajiyera basne chan.\n\nFeri eutai kakshyama basera,\nEutailai jiskaudai hasne din kaha farkela ra?\n\nSamaya farke na farke,\nAba antyama sabai sadhai sangai hune bacha haru pani chutine chan.\n\nAdhura maya ka katha,\nMitratako bichhod,\nYi sabai le kehi amulya paath sikayeko cha.\n\nSuru bhayeko kura ta ekdin antya hune nai rahecha.\nAba antyama,\nChhodi janu nai parne rahecha.\n\nChhodi jana sakula ra kasari?\nRakhana na malai yetai katai.\n\nBasaune bas nai rahena bhane pani,\nSamjhana mai samhalnu hai malai.",
    "meaning": "This poem is a farewell to school, childhood, teachers, friendships, and the memories that quietly shape us. It reflects on how ordinary moments become priceless only after they have passed, reminding us that every ending leaves behind something worth carrying forever.",
    "authorNotes": "This was one of the first poems I ever shared publicly. It was inspired by leaving school and realizing that the place I once wanted to leave had become the place I missed the most.",
    "inspiration": "School farewell, Bhanu Smarika writings, teachers, friendships, and the bittersweet feeling of growing up.",
    "instagramUrl": "https://www.instagram.com/uwyiz_/",
    "shareUrl": "https://yourdomain.com/poems/bilauney-chan-yi-yaad-haru",
    "views": 0,
    "likes": 0,
    "bookmarks": 0,
    "relatedPoems": [
      1,
      4
    ],
    "seoTitle": "Bilauney Chan Yi Yaad Haru | A Nepali Farewell Poem",
    "seoDescription": "A heartfelt Nepali poem about school memories, friendship, growing up, and the people we never truly leave behind.",
    "altText": "A nostalgic school corridor at sunset, symbolizing memories and farewell.",
    "colorTheme": "#C29A63",
    "language": "Nepali",
    "visibility": "published",
    "draft": false
  },
  {
    "id": 2,
    "title": "Haraeka Aasha Ani Aastha",
    "subtitle": "Faith should never become a weapon against humanity.",
    "slug": "haraeka-aasha-ani-aastha",
    "caption": "A spoken-word poem questioning the exploitation of faith and the suffering justified in the name of God.",
    "quote": "Aakhir antyama ti phool chadhauneharu pani ta metidai jane rahechhan.",
    "category": "Society",
    "tags": [
      "society",
      "faith",
      "humanity",
      "justice",
      "religion",
      "social commentary",
      "spoken word"
    ],
    "mood": "thought-provoking",
    "duration": "1 min 38 sec",
    "readingTime": "2 min",
    "publishDate": "2025-05-05",
    "featured": true,
    "thumbnail": "assets/thumbnails/harayeko_aasha.jpg",
    "heroImage": "assets/thumbnails/harayeko_aasha.jpg",
    "video": "assets/videos/harayekoaasha.mp4",
    "poster": "assets/thumbnails/harayeko_aasha.jpg",
    "audioOnly": false,
    "fullPoem": "Haraeka aasha ani aastha.\n\nBhanchhan Ishwar parkhaune ani timi parkhane. Tara parkhinda parkhinda pani timi parkhana chai nachhodnu hai. Thalima phool sajaai rakhnu timi. Bholi mrityupachhi pani arko juni jiune prayatna prapta garnu chha re.\n\nDevata mandina ta bhandina ma, tara Saraswati puji dhanko aasha rakhchhau timi sayad. Bhagwanko aastha nai nabhaidiyeko bhaye ek pujariko lagi aafno dhan khera faldainthyau hola timile. Sharir usko ghisriyer kharani hudai chha ra ajhai pani kayaule aafno dhoopko dhuwaamai dhalma lyaudai Ishwarko jawafko lagi parkhirahichhan. Aafno swarthale Bhagwanko murtibhitra bere bechne uni.\n\nBhakal garna lanchhu bhandai mandirkai agadi kayau nari sopidieka chhan tinile. Aaja ek barsha bhaisakyo. Ahilesamma pani Sarita didiko kapadabat dhusi lageko ragat ganaaunchha. Dharmako naamma ti adharmile unko aasha namaridiyeko bhaye sayad, sayad aaja Sarita didi jiundai po hunthin ki?\n\nAakhir antyama ti phool chadhauneharu pani ta metidai jane rahechhan.",
    "meaning": "This poem is not an attack on faith or religion. Instead, it questions how belief can be manipulated by people for power, profit, and control. It asks whether humanity is sometimes forgotten when rituals become more important than compassion, and reminds us that no act committed in the name of God can justify injustice.",
    "authorNotes": "I wrote this to separate faith from exploitation. The poem challenges the misuse of religion while respecting the personal beliefs of those who practice it with kindness and humanity.",
    "inspiration": "Stories of people who suffered because trust, devotion, and religious authority were abused, and the realization that compassion should always stand above blind obedience.",
    "instagramUrl": "https://www.instagram.com/reel/DJRS09PTwt1/",
    "shareUrl": "https://yourdomain.com/poems/haraeka-aasha-ani-aastha",
    "views": 0,
    "likes": 0,
    "bookmarks": 0,
    "relatedPoems": [
      6,
      7
    ],
    "seoTitle": "Haraeka Aasha Ani Aastha | A Nepali Spoken Word on Faith and Humanity",
    "seoDescription": "A thought-provoking Nepali spoken-word poem examining the misuse of faith, religious exploitation, and the importance of compassion over blind belief.",
    "altText": "A dimly lit temple with fading flowers and incense smoke, symbolizing faith, loss, and reflection.",
    "colorTheme": "#6B4A3A",
    "language": "Nepali",
    "visibility": "published",
    "draft": false
  },
  {
    "id": 4,
    "title": "Samjhanako Sajh",
    "subtitle": "Every sunset carries a dream that chose to become a memory.",
    "slug": "samjhanako-sajh",
    "caption": "A poem about accepting unfinished dreams and finding peace in the paths destiny quietly rewrites.",
    "quote": "Gham pani ta astaunu parchha... hami kina nasakne?",
    "category": "Hope",
    "tags": [
      "hope",
      "dreams",
      "destiny",
      "acceptance",
      "life",
      "healing",
      "nostalgia"
    ],
    "mood": "reflective",
    "duration": "1 min 1 sec",
    "readingTime": "2 min",
    "publishDate": "2025-06-25",
    "featured": true,
    "thumbnail": "assets/thumbnails/bipana.jpg",
    "heroImage": "assets/thumbnails/bipana.jpg",
    "video": "assets/videos/bipana.mp4",
    "poster": "assets/thumbnails/bipana.jpg",
    "audioOnly": false,
    "fullPoem": "Samjhanako sajh...\n\nKahile kahi,\nJindagile socheko bato roj्दaina.\nHami sapana buniranchhau,\nTara bhagyele afnai kahani lekhiraheko hunchha.\n\nKati sapana adhurai rahanchan,\nKati ichchha samayale sangai lagidinchha.\nTara adhurai bhayeka sapanaharu pani,\nHamilai banauchan.\n\nAstaudai gareko ghamlai hera,\nUsle pani afno ujyalo chhadera janu parchha.\nTara bholi feri udaya hunchha.\n\nTyasaile,\nAdhurapan sanga darau nakhos.\nKehi sapana pura hunchan,\nKehi samjhana banchan.\n\nRa kahile kahi,\nSamjhanako sajh nai,\nJeevanako sabai bhanda sundar rang hunchha.",
    "meaning": "This poem reflects on the dreams we couldn't fulfill and the reality that destiny sometimes leads us somewhere unexpected. Rather than seeing unfinished dreams as failures, it encourages us to embrace them as beautiful parts of our journey. Just as every sunset marks an ending before another sunrise, every ending carries the possibility of a new beginning.",
    "authorNotes": "I wrote this after realizing that not every dream is meant to come true. Some dreams exist only to shape who we become, and there is beauty in accepting that.",
    "inspiration": "The setting sun, unfinished dreams, and the quiet realization that destiny often writes a different story than the one we imagined.",
    "instagramUrl": "https://www.instagram.com/reel/DJRS09PTwt1/",
    "shareUrl": "https://yourdomain.com/poems/samjhanako-sajh",
    "views": 7895,
    "likes": 3458,
    "bookmarks": 1258,
    "relatedPoems": [
      5,
      6
    ],
    "seoTitle": "Samjhanako Sajh | A Nepali Poem About Unfinished Dreams",
    "seoDescription": "A heartfelt Nepali spoken-word poem about accepting destiny, unfinished dreams, and discovering beauty in every ending.",
    "altText": "A golden sunset over distant hills, symbolizing hope, acceptance, and the beauty of unfinished dreams.",
    "colorTheme": "#E09A5B",
    "language": "Nepali",
    "visibility": "published",
    "draft": false
  },
  {
    "id": 5,
    "title": "Tuteka Tara",
    "subtitle": "Tuteka tara pani ta antim ma bilaune rahechan.",
    "slug": "tuteka-tara",
    "caption": "A poem about the quiet terror of being forgotten after the last person who remembers you is gone.",
    "quote": "Ma sarir matra pani ta thiena... tara aaja tyo sarir bina, ma ko nai po hu ra?",
    "category": "Existence",
    "tags": [
      "existence",
      "memory",
      "death",
      "identity",
      "loneliness",
      "impermanence"
    ],
    "mood": "melancholy",
    "duration": "1 min 5 sec",
    "readingTime": "1 min",
    "publishDate": "2025-12-22",
    "featured": true,
    "thumbnail": "assets/thumbnails/tuteka tara.jpg",
    "heroImage": "assets/thumbnails/tuteka tara.jpg",
    "video": "assets/videos/tuteka tara.mp4",
    "poster": "assets/thumbnails/tuteka tara.jpg",
    "audioOnly": false,
    "fullPoem": "Tuteka tara pani ta antim ma bilaune rahechan.\n\nMa aafno parchhai ma aaja harayeko chu.\nAarighaatka aagoma udera gaeko dhuwajastai,\nma pani kahilekai bilayera jaanchhu.\n\nMa mareko din ma,\nmalai samjhine timi pani ek din bilauchau.\nAni tespachi,\nma ko smritima baachne?\n\nBiteka rituharu aaja bihani parkadai chan.\nHarek raat ma eklai hune tara haru,\naaja afai eklai chan.\n\nMa banchhu,\nbujhchu,\nani bistarai ma afai bilaunchhu.\n\nMa sarir matra pani ta thiena.\nTara aaja,\ntyo sarir bina,\nma...\nko nai po hu ra?",
    "meaning": "This poem confronts the inevitability of being forgotten. It reflects on how every relationship, every memory, and even the people who remember us will eventually disappear. When the final witness to our existence is gone, the poem asks whether any part of us truly remains. It is less about death itself and more about the fragile nature of identity, memory, and human existence.",
    "authorNotes": "Written while reflecting on the unsettling realization that one day, even the people who remember us will no longer be here. The poem became an exploration of what remains when memory itself dies.",
    "inspiration": "The thought that everyone eventually experiences a 'second death'—the moment the last person who remembers them is gone.",
    "instagramUrl": "https://www.instagram.com/reel/DSkH2RMj774/",
    "shareUrl": "https://yourdomain.com/poems/tuteka-tara",
    "views": 0,
    "likes": 0,
    "bookmarks": 0,
    "relatedPoems": [],
    "seoTitle": "Tuteka Tara | A Poem on Memory, Death & Identity",
    "seoDescription": "A Nepali spoken-word poem exploring memory, mortality, identity, and the quiet fear of being forgotten.",
    "altText": "A solitary night sky with a fading broken star symbolizing memory and impermanence.",
    "colorTheme": "#2B3247",
    "language": "Nepali",
    "visibility": "published",
    "draft": false
  },
  {
    "id": 6,
    "title": "Smritiko Jhyalale Sanchera Rakheko Hawa",
    "subtitle": "Some souls leave our lives, but never our hearts.",
    "slug": "smritiko-jhyalale-sanchera-rakheko-hawa",
    "caption": "A poem about the kind of love that never truly disappears, even when the person does.",
    "quote": "Sakne bhaye sakne bhanda pani badhi... ma sadaiv timrai chhayale rangaauna khojnechhu.",
    "category": "Love",
    "tags": [
      "love",
      "memory",
      "devotion",
      "longing",
      "separation",
      "nostalgia",
      "spoken word"
    ],
    "mood": "melancholic",
    "duration": "41 sec",
    "readingTime": "1 min",
    "publishDate": "2025-09-13",
    "featured": true,
    "thumbnail": "assets/thumbnails/smritikojhyalley.jpg",
    "heroImage": "assets/thumbnails/smritikojhyalley.jpg",
    "video": "assets/videos/smieiti.mp4",
    "poster": "assets/thumbnails/smritikojhyalley.jpg",
    "audioOnly": false,
    "fullPoem": "Smritiko jhyalale sanchera rakheko hawa,\nAaja arkai batassanga magn chha.\n\nDulechhu feri.\nTyahi aakashkai aankhabhitra haraeko aasu,\nSayad hawakai batasanga bilaudai chhan.\n\nAasu dhune kramma,\nAasu birseka ti mayaka malami,\nTimi timibhitra nai haraeko chhau aaja.\n\nJaleko pida,\nRagatle bhije pani,\nRang ta ajhai jiwit nai ta chha.\n\nSakne bhaye,\nSakne bhanda pani badhi,\nTyahi rittiyeko samarpanma bhijeko ragatle bhaye pani,\nMa sadaiv timrai chhayale rangaauna khojnechhu.\n\nBiralo baat.",
    "meaning": "This poem explores the strange permanence of love. Even after people leave, the emotions they awakened continue to live within us. It reflects on devotion that survives distance, loss, and time—not because we refuse to let go, but because some connections quietly become part of who we are.",
    "authorNotes": "I wrote this while reflecting on how memories outlive relationships. Sometimes love doesn't ask to be remembered—it simply remains.",
    "inspiration": "The quiet realization that some people become part of our inner world forever, even after they are gone from our lives.",
    "instagramUrl": "https://www.instagram.com/uwyiz_/",
    "shareUrl": "https://yourdomain.com/poems/smritiko-jhyalale-sanchera-rakheko-hawa",
    "views": 0,
    "likes": 0,
    "bookmarks": 0,
    "relatedPoems": [
      1,
      6
    ],
    "seoTitle": "Smritiko Jhyalale Sanchera Rakheko Hawa | A Nepali Poem on Memory and Devotion",
    "seoDescription": "A heartfelt Nepali spoken-word poem about memories, quiet devotion, longing, and the kind of love that never truly leaves.",
    "altText": "An open window with soft evening light and wind flowing through sheer curtains, symbolizing lingering memories and enduring love.",
    "colorTheme": "#7A5F58",
    "language": "Nepali",
    "visibility": "published",
    "draft": false
  }
];
